export type User = {
  id: number;
  username?: string | null;
  code?: string | null;
  name: string;
  email?: string | null;
  phone?: string | null;
  address?: string | null;
  citizen_id?: string | null;
  citizen_id_place?: string | null;
  hire_date?: string | null;
  role?: string | null;
  status: string;
  auth_status?: string | null;
  invite_sent_at?: string | null;
  invite_accepted_at?: string | null;
  department_id?: number | null;
  created_at: string;
  deleted_at?: string | null;
};
