from __future__ import annotations

from sqlalchemy import Engine, text


def _get_column_meta(engine: Engine, *, table: str, column: str, schema: str) -> dict[str, object] | None:
    q = text(
        """
        SELECT COLUMN_TYPE, IS_NULLABLE, COLUMN_DEFAULT
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = :schema AND TABLE_NAME = :table AND COLUMN_NAME = :column
        LIMIT 1
        """
    )
    with engine.connect() as conn:
        row = conn.execute(q, {"schema": schema, "table": table, "column": column}).mappings().first()
        return dict(row) if row is not None else None


def _column_exists(engine: Engine, *, table: str, column: str, schema: str) -> bool:
    q = text(
        """
        SELECT COUNT(*) AS c
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = :schema AND TABLE_NAME = :table AND COLUMN_NAME = :column
        """
    )
    with engine.connect() as conn:
        c = conn.execute(q, {"schema": schema, "table": table, "column": column}).scalar_one()
        return int(c or 0) > 0


def _table_exists(engine: Engine, *, table: str, schema: str) -> bool:
    q = text(
        """
        SELECT COUNT(*) AS c
        FROM INFORMATION_SCHEMA.TABLES
        WHERE TABLE_SCHEMA = :schema AND TABLE_NAME = :table
        """
    )
    with engine.connect() as conn:
        c = conn.execute(q, {"schema": schema, "table": table}).scalar_one()
        return int(c or 0) > 0


def _exec(engine: Engine, sql: str) -> None:
    with engine.begin() as conn:
        conn.execute(text(sql))

def _index_exists(engine: Engine, *, table: str, index: str, schema: str) -> bool:
    q = text(
        """
        SELECT COUNT(*) AS c
        FROM INFORMATION_SCHEMA.STATISTICS
        WHERE TABLE_SCHEMA = :schema AND TABLE_NAME = :table AND INDEX_NAME = :index
        """
    )
    with engine.connect() as conn:
        c = conn.execute(q, {"schema": schema, "table": table, "index": index}).scalar_one()
        return int(c or 0) > 0


def _list_unique_single_column_indexes(
    engine: Engine, *, table: str, column: str, schema: str
) -> list[str]:
    """
    Return names of UNIQUE indexes that cover exactly one column and that column matches `column`.

    This is used to clean up older schemas where `email` might have had a global UNIQUE constraint
    with a different index name (e.g. auto-generated by a previous ORM/migration).
    """
    q = text(
        """
        SELECT INDEX_NAME
        FROM INFORMATION_SCHEMA.STATISTICS
        WHERE TABLE_SCHEMA = :schema
          AND TABLE_NAME = :table
          AND NON_UNIQUE = 0
        GROUP BY INDEX_NAME
        HAVING COUNT(*) = 1
           AND SUM(CASE WHEN COLUMN_NAME = :column THEN 1 ELSE 0 END) = 1
        """
    )
    with engine.connect() as conn:
        rows = conn.execute(q, {"schema": schema, "table": table, "column": column}).all()
        return [r[0] for r in rows if r and r[0] and str(r[0]).upper() != "PRIMARY"]


def run_lightweight_migrations(engine: Engine, *, schema: str) -> None:
    """
    Minimal, non-Alembic migrations for local/dev:
    - Add missing columns for business fields (users, departments)
    This is best-effort: safe to run multiple times.
    """

    # users table extensions (if project was created before these fields existed)
    if not _column_exists(engine, table="users", column="company_id", schema=schema):
        _exec(engine, "ALTER TABLE users ADD COLUMN company_id INT NULL, ADD KEY ix_users_company_id (company_id)")
    if not _column_exists(engine, table="users", column="username", schema=schema):
        _exec(engine, "ALTER TABLE users ADD COLUMN username VARCHAR(64) NULL, ADD UNIQUE KEY uq_users_username (username), ADD KEY ix_users_username (username)")
    if not _column_exists(engine, table="users", column="password_hash", schema=schema):
        _exec(engine, "ALTER TABLE users ADD COLUMN password_hash VARCHAR(255) NULL")
    if not _column_exists(engine, table="users", column="auth_status", schema=schema):
        _exec(engine, "ALTER TABLE users ADD COLUMN auth_status VARCHAR(16) NOT NULL DEFAULT 'active'")
    if not _column_exists(engine, table="users", column="invite_token_hash", schema=schema):
        _exec(engine, "ALTER TABLE users ADD COLUMN invite_token_hash VARCHAR(255) NULL")
    if not _column_exists(engine, table="users", column="invite_token_expires_at", schema=schema):
        _exec(engine, "ALTER TABLE users ADD COLUMN invite_token_expires_at DATETIME NULL")
    if not _column_exists(engine, table="users", column="invite_sent_at", schema=schema):
        _exec(engine, "ALTER TABLE users ADD COLUMN invite_sent_at DATETIME NULL")
    if not _column_exists(engine, table="users", column="invite_accepted_at", schema=schema):
        _exec(engine, "ALTER TABLE users ADD COLUMN invite_accepted_at DATETIME NULL")
    if not _column_exists(engine, table="users", column="code", schema=schema):
        _exec(engine, "ALTER TABLE users ADD COLUMN code VARCHAR(32) NULL")
    # Employee code uniqueness is scoped to company: allow same code across different companies.
    if _index_exists(engine, table="users", index="uq_users_code", schema=schema):
        _exec(engine, "ALTER TABLE users DROP INDEX uq_users_code")
    for idx in _list_unique_single_column_indexes(engine, table="users", column="code", schema=schema):
        _exec(engine, f"ALTER TABLE users DROP INDEX {idx}")
    if not _index_exists(engine, table="users", index="uq_users_company_code", schema=schema):
        _exec(engine, "ALTER TABLE users ADD UNIQUE KEY uq_users_company_code (company_id, code)")
    if not _column_exists(engine, table="users", column="email", schema=schema):
        _exec(engine, "ALTER TABLE users ADD COLUMN email VARCHAR(255) NULL")
    # Email uniqueness is scoped to company: allow same email across different companies.
    if _index_exists(engine, table="users", index="uq_users_email", schema=schema):
        _exec(engine, "ALTER TABLE users DROP INDEX uq_users_email")
    # Drop any legacy global UNIQUE(email) index regardless of its name.
    for idx in _list_unique_single_column_indexes(engine, table="users", column="email", schema=schema):
        _exec(engine, f"ALTER TABLE users DROP INDEX {idx}")
    if not _index_exists(engine, table="users", index="uq_users_company_email", schema=schema):
        _exec(engine, "ALTER TABLE users ADD UNIQUE KEY uq_users_company_email (company_id, email)")
    if not _index_exists(engine, table="users", index="ix_users_email", schema=schema):
        _exec(engine, "ALTER TABLE users ADD KEY ix_users_email (email)")
    if not _column_exists(engine, table="users", column="role", schema=schema):
        _exec(engine, "ALTER TABLE users ADD COLUMN role VARCHAR(64) NULL")
    if not _column_exists(engine, table="users", column="status", schema=schema):
        _exec(engine, "ALTER TABLE users ADD COLUMN status VARCHAR(16) NOT NULL DEFAULT 'active'")
    if not _column_exists(engine, table="users", column="department_id", schema=schema):
        _exec(engine, "ALTER TABLE users ADD COLUMN department_id INT NULL, ADD KEY ix_users_department_id (department_id)")

    # departments table extensions
    if not _column_exists(engine, table="departments", column="company_id", schema=schema):
        _exec(engine, "ALTER TABLE departments ADD COLUMN company_id INT NULL, ADD KEY ix_departments_company_id (company_id)")

    # companies table extensions (geo-fence settings)
    if _table_exists(engine, table="companies", schema=schema):
        if not _column_exists(engine, table="companies", column="address", schema=schema):
            _exec(engine, "ALTER TABLE companies ADD COLUMN address VARCHAR(255) NULL")
        if not _column_exists(engine, table="companies", column="latitude", schema=schema):
            _exec(engine, "ALTER TABLE companies ADD COLUMN latitude DOUBLE NULL")
        if not _column_exists(engine, table="companies", column="longitude", schema=schema):
            _exec(engine, "ALTER TABLE companies ADD COLUMN longitude DOUBLE NULL")
        if not _column_exists(engine, table="companies", column="logo_blob", schema=schema):
            _exec(engine, "ALTER TABLE companies ADD COLUMN logo_blob MEDIUMBLOB NULL")
        if not _column_exists(engine, table="companies", column="logo_mime_type", schema=schema):
            _exec(engine, "ALTER TABLE companies ADD COLUMN logo_mime_type VARCHAR(64) NULL")
    if not _column_exists(engine, table="companies", column="geo_radius_meters", schema=schema):
        _exec(engine, "ALTER TABLE companies ADD COLUMN geo_radius_meters DOUBLE NULL")
    if not _column_exists(engine, table="companies", column="require_gps_on_attendance", schema=schema):
        _exec(engine, "ALTER TABLE companies ADD COLUMN require_gps_on_attendance TINYINT(1) NOT NULL DEFAULT 0")

    # IAM join tables (new): user_roles, user_permissions
    if not _table_exists(engine, table="user_roles", schema=schema):
        _exec(
            engine,
            """
            CREATE TABLE user_roles (
              id INT AUTO_INCREMENT PRIMARY KEY,
              user_id INT NOT NULL,
              role_id INT NOT NULL,
              created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
              UNIQUE KEY uq_user_roles (user_id, role_id),
              KEY ix_user_roles_user_id (user_id),
              KEY ix_user_roles_role_id (role_id),
              CONSTRAINT fk_user_roles_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
              CONSTRAINT fk_user_roles_role_id FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
            )
            """,
        )
    if not _table_exists(engine, table="user_permissions", schema=schema):
        _exec(
            engine,
            """
            CREATE TABLE user_permissions (
              id INT AUTO_INCREMENT PRIMARY KEY,
              user_id INT NOT NULL,
              permission_id INT NOT NULL,
              created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
              UNIQUE KEY uq_user_permissions (user_id, permission_id),
              KEY ix_user_permissions_user_id (user_id),
              KEY ix_user_permissions_permission_id (permission_id),
              CONSTRAINT fk_user_permissions_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
              CONSTRAINT fk_user_permissions_permission_id FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
            )
            """,
        )

    # Best-effort data migration from legacy IAM tables (accounts/account_roles/account_permissions).
    if _table_exists(engine, table="accounts", schema=schema):
        try:
            # 1) Move account rows into users (by username).
            _exec(
                engine,
                """
                INSERT IGNORE INTO users (username, password_hash, name)
                SELECT a.username, a.password_hash, a.username
                FROM accounts a
                """,
            )
            # 2) Move role assignments by username mapping.
            if _table_exists(engine, table="account_roles", schema=schema):
                _exec(
                    engine,
                    """
                    INSERT IGNORE INTO user_roles (user_id, role_id)
                    SELECT u.id, ar.role_id
                    FROM account_roles ar
                    JOIN accounts a ON a.id = ar.account_id
                    JOIN users u ON u.username = a.username
                    """,
                )
            # 3) Move direct permission assignments by username mapping.
            if _table_exists(engine, table="account_permissions", schema=schema):
                _exec(
                    engine,
                    """
                    INSERT IGNORE INTO user_permissions (user_id, permission_id)
                    SELECT u.id, ap.permission_id
                    FROM account_permissions ap
                    JOIN accounts a ON a.id = ap.account_id
                    JOIN users u ON u.username = a.username
                    """,
                )
        except Exception:
            # Migration is best-effort; ignore any failures due to partial schema differences.
            pass

    # attendance_policies table extensions
    if not _column_exists(engine, table="attendance_policies", column="timezone", schema=schema):
        _exec(engine, "ALTER TABLE attendance_policies ADD COLUMN timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Ho_Chi_Minh'")
    if not _column_exists(engine, table="attendance_policies", column="face_match_threshold", schema=schema):
        _exec(engine, "ALTER TABLE attendance_policies ADD COLUMN face_match_threshold DOUBLE NOT NULL DEFAULT 0.5")
    if not _column_exists(engine, table="attendance_policies", column="shift_end", schema=schema):
        _exec(engine, "ALTER TABLE attendance_policies ADD COLUMN shift_end VARCHAR(5) NOT NULL DEFAULT '18:00'")
    if not _column_exists(engine, table="attendance_policies", column="early_leave_grace_minutes", schema=schema):
        _exec(engine, "ALTER TABLE attendance_policies ADD COLUMN early_leave_grace_minutes INT NOT NULL DEFAULT 0")
    if not _column_exists(engine, table="attendance_policies", column="break_start", schema=schema):
        _exec(engine, "ALTER TABLE attendance_policies ADD COLUMN break_start VARCHAR(5) NOT NULL DEFAULT '12:00'")
    if not _column_exists(engine, table="attendance_policies", column="break_end", schema=schema):
        _exec(engine, "ALTER TABLE attendance_policies ADD COLUMN break_end VARCHAR(5) NOT NULL DEFAULT '13:00'")
    if not _column_exists(engine, table="attendance_policies", column="break_duration_minutes", schema=schema):
        _exec(engine, "ALTER TABLE attendance_policies ADD COLUMN break_duration_minutes INT NOT NULL DEFAULT 60")
    if not _column_exists(engine, table="attendance_policies", column="break_threshold_hours", schema=schema):
        _exec(engine, "ALTER TABLE attendance_policies ADD COLUMN break_threshold_hours DOUBLE NOT NULL DEFAULT 6.0")
    if not _column_exists(engine, table="attendance_policies", column="auto_checkout_time", schema=schema):
        _exec(engine, "ALTER TABLE attendance_policies ADD COLUMN auto_checkout_time VARCHAR(5) NOT NULL DEFAULT '23:59'")
    if not _column_exists(engine, table="attendance_policies", column="checkin_from", schema=schema):
        _exec(engine, "ALTER TABLE attendance_policies ADD COLUMN checkin_from VARCHAR(5) NOT NULL DEFAULT '06:00'")
    if not _column_exists(engine, table="attendance_policies", column="checkin_to", schema=schema):
        _exec(engine, "ALTER TABLE attendance_policies ADD COLUMN checkin_to VARCHAR(5) NOT NULL DEFAULT '12:00'")
    if not _column_exists(engine, table="attendance_policies", column="checkout_from", schema=schema):
        _exec(engine, "ALTER TABLE attendance_policies ADD COLUMN checkout_from VARCHAR(5) NOT NULL DEFAULT '12:00'")
    if not _column_exists(engine, table="attendance_policies", column="checkout_to", schema=schema):
        _exec(engine, "ALTER TABLE attendance_policies ADD COLUMN checkout_to VARCHAR(5) NOT NULL DEFAULT '23:00'")
    if not _column_exists(engine, table="attendance_policies", column="min_minutes_between_same_type", schema=schema):
        _exec(engine, "ALTER TABLE attendance_policies ADD COLUMN min_minutes_between_same_type INT NOT NULL DEFAULT 2")
    if not _column_exists(engine, table="attendance_policies", column="updated_at", schema=schema):
        _exec(
            engine,
            "ALTER TABLE attendance_policies ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP",
        )

    # company_attendance_policies table extensions
    if _table_exists(engine, table="company_attendance_policies", schema=schema):
        if not _column_exists(engine, table="company_attendance_policies", column="timezone", schema=schema):
            _exec(engine, "ALTER TABLE company_attendance_policies ADD COLUMN timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Ho_Chi_Minh'")
        if not _column_exists(engine, table="company_attendance_policies", column="face_match_threshold", schema=schema):
            _exec(engine, "ALTER TABLE company_attendance_policies ADD COLUMN face_match_threshold DOUBLE NOT NULL DEFAULT 0.5")
        if not _column_exists(engine, table="company_attendance_policies", column="shift_start", schema=schema):
            _exec(engine, "ALTER TABLE company_attendance_policies ADD COLUMN shift_start VARCHAR(5) NOT NULL DEFAULT '09:00'")
        if not _column_exists(engine, table="company_attendance_policies", column="shift_end", schema=schema):
            _exec(engine, "ALTER TABLE company_attendance_policies ADD COLUMN shift_end VARCHAR(5) NOT NULL DEFAULT '18:00'")
        if not _column_exists(engine, table="company_attendance_policies", column="late_grace_minutes", schema=schema):
            _exec(engine, "ALTER TABLE company_attendance_policies ADD COLUMN late_grace_minutes INT NOT NULL DEFAULT 0")
        if not _column_exists(engine, table="company_attendance_policies", column="early_leave_grace_minutes", schema=schema):
            _exec(engine, "ALTER TABLE company_attendance_policies ADD COLUMN early_leave_grace_minutes INT NOT NULL DEFAULT 0")
        if not _column_exists(engine, table="company_attendance_policies", column="break_start", schema=schema):
            _exec(engine, "ALTER TABLE company_attendance_policies ADD COLUMN break_start VARCHAR(5) NOT NULL DEFAULT '12:00'")
        if not _column_exists(engine, table="company_attendance_policies", column="break_end", schema=schema):
            _exec(engine, "ALTER TABLE company_attendance_policies ADD COLUMN break_end VARCHAR(5) NOT NULL DEFAULT '13:00'")
        if not _column_exists(engine, table="company_attendance_policies", column="break_duration_minutes", schema=schema):
            _exec(engine, "ALTER TABLE company_attendance_policies ADD COLUMN break_duration_minutes INT NOT NULL DEFAULT 60")
        if not _column_exists(engine, table="company_attendance_policies", column="break_threshold_hours", schema=schema):
            _exec(engine, "ALTER TABLE company_attendance_policies ADD COLUMN break_threshold_hours DOUBLE NOT NULL DEFAULT 6.0")
        if not _column_exists(engine, table="company_attendance_policies", column="auto_checkout_time", schema=schema):
            _exec(engine, "ALTER TABLE company_attendance_policies ADD COLUMN auto_checkout_time VARCHAR(5) NOT NULL DEFAULT '23:59'")
        if not _column_exists(engine, table="company_attendance_policies", column="checkin_from", schema=schema):
            _exec(engine, "ALTER TABLE company_attendance_policies ADD COLUMN checkin_from VARCHAR(5) NOT NULL DEFAULT '06:00'")
        if not _column_exists(engine, table="company_attendance_policies", column="checkin_to", schema=schema):
            _exec(engine, "ALTER TABLE company_attendance_policies ADD COLUMN checkin_to VARCHAR(5) NOT NULL DEFAULT '12:00'")
        if not _column_exists(engine, table="company_attendance_policies", column="checkout_from", schema=schema):
            _exec(engine, "ALTER TABLE company_attendance_policies ADD COLUMN checkout_from VARCHAR(5) NOT NULL DEFAULT '12:00'")
        if not _column_exists(engine, table="company_attendance_policies", column="checkout_to", schema=schema):
            _exec(engine, "ALTER TABLE company_attendance_policies ADD COLUMN checkout_to VARCHAR(5) NOT NULL DEFAULT '23:00'")
        if not _column_exists(engine, table="company_attendance_policies", column="min_minutes_between_same_type", schema=schema):
            _exec(engine, "ALTER TABLE company_attendance_policies ADD COLUMN min_minutes_between_same_type INT NOT NULL DEFAULT 2")
        if not _column_exists(engine, table="company_attendance_policies", column="updated_at", schema=schema):
            _exec(
                engine,
                "ALTER TABLE company_attendance_policies ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP",
            )

    # users table extensions
    if not _column_exists(engine, table="users", column="face_enrolled_at", schema=schema):
        _exec(engine, "ALTER TABLE users ADD COLUMN face_enrolled_at DATETIME NULL")

    # attendance_logs geo fields
    if not _column_exists(engine, table="attendance_logs", column="latitude", schema=schema):
        _exec(engine, "ALTER TABLE attendance_logs ADD COLUMN latitude DOUBLE NULL")
    if not _column_exists(engine, table="attendance_logs", column="longitude", schema=schema):
        _exec(engine, "ALTER TABLE attendance_logs ADD COLUMN longitude DOUBLE NULL")
    if not _column_exists(engine, table="attendance_logs", column="distance_meters", schema=schema):
        _exec(engine, "ALTER TABLE attendance_logs ADD COLUMN distance_meters DOUBLE NULL")
    if not _column_exists(engine, table="attendance_logs", column="geo_ok", schema=schema):
        _exec(engine, "ALTER TABLE attendance_logs ADD COLUMN geo_ok TINYINT(1) NOT NULL DEFAULT 1")

    # attendance evidence settings / history / queue
    try:
        if not _table_exists(engine, table="attendance_evidence_settings", schema=schema):
            _exec(
                engine,
                """
                CREATE TABLE attendance_evidence_settings (
                    company_id INT NOT NULL,
                    enable_evidence_image TINYINT(1) NOT NULL DEFAULT 1,
                    image_quality INT NOT NULL DEFAULT 65,
                    image_max_width INT NOT NULL DEFAULT 720,
                    image_format VARCHAR(16) NOT NULL DEFAULT 'webp',
                    image_retention_days INT NOT NULL DEFAULT 30,
                    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                    PRIMARY KEY (company_id),
                    CONSTRAINT fk_attendance_evidence_settings_company
                        FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
                """,
            )
        if not _table_exists(engine, table="attendance_history", schema=schema):
            _exec(
                engine,
                """
                CREATE TABLE attendance_history (
                    id INT NOT NULL AUTO_INCREMENT,
                    company_id INT NULL,
                    employee_id INT NOT NULL,
                    attendance_log_id INT NULL,
                    type VARCHAR(16) NOT NULL,
                    check_time DATETIME NOT NULL,
                    confidence_score DOUBLE NOT NULL,
                    image_url VARCHAR(512) NULL,
                    image_size_kb INT NULL,
                    image_format VARCHAR(16) NULL,
                    upload_status VARCHAR(16) NOT NULL DEFAULT 'pending',
                    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                    PRIMARY KEY (id),
                    UNIQUE KEY uq_attendance_history_log_id (attendance_log_id),
                    KEY ix_attendance_history_company_id (company_id),
                    KEY ix_attendance_history_employee_id (employee_id),
                    KEY ix_attendance_history_type (type),
                    KEY ix_attendance_history_check_time (check_time),
                    KEY ix_attendance_history_upload_status (upload_status),
                    CONSTRAINT fk_attendance_history_company
                        FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
                    CONSTRAINT fk_attendance_history_employee
                        FOREIGN KEY (employee_id) REFERENCES users(id) ON DELETE CASCADE,
                    CONSTRAINT fk_attendance_history_log
                        FOREIGN KEY (attendance_log_id) REFERENCES attendance_logs(id) ON DELETE SET NULL
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
                """,
            )
        if not _table_exists(engine, table="attendance_evidence_tasks", schema=schema):
            _exec(
                engine,
                """
                CREATE TABLE attendance_evidence_tasks (
                    id INT NOT NULL AUTO_INCREMENT,
                    history_id INT NOT NULL,
                    company_id INT NULL,
                    employee_id INT NOT NULL,
                    spool_path VARCHAR(512) NOT NULL,
                    source_mime VARCHAR(64) NULL,
                    status VARCHAR(16) NOT NULL DEFAULT 'pending',
                    attempts INT NOT NULL DEFAULT 0,
                    max_attempts INT NOT NULL DEFAULT 3,
                    next_attempt_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    last_error TEXT NULL,
                    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                    completed_at DATETIME NULL,
                    PRIMARY KEY (id),
                    UNIQUE KEY uq_attendance_evidence_tasks_history_id (history_id),
                    KEY ix_attendance_evidence_tasks_company_id (company_id),
                    KEY ix_attendance_evidence_tasks_employee_id (employee_id),
                    KEY ix_attendance_evidence_tasks_status (status),
                    KEY ix_attendance_evidence_tasks_next_attempt_at (next_attempt_at),
                    CONSTRAINT fk_attendance_evidence_tasks_history
                        FOREIGN KEY (history_id) REFERENCES attendance_history(id) ON DELETE CASCADE,
                    CONSTRAINT fk_attendance_evidence_tasks_company
                        FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
                    CONSTRAINT fk_attendance_evidence_tasks_employee
                        FOREIGN KEY (employee_id) REFERENCES users(id) ON DELETE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
                """,
            )

        if _table_exists(engine, table="attendance_history", schema=schema):
            if not _column_exists(engine, table="attendance_history", column="company_id", schema=schema):
                _exec(engine, "ALTER TABLE attendance_history ADD COLUMN company_id INT NULL, ADD KEY ix_attendance_history_company_id (company_id)")
            if not _column_exists(engine, table="attendance_history", column="employee_id", schema=schema):
                _exec(engine, "ALTER TABLE attendance_history ADD COLUMN employee_id INT NOT NULL, ADD KEY ix_attendance_history_employee_id (employee_id)")
            if not _column_exists(engine, table="attendance_history", column="attendance_log_id", schema=schema):
                _exec(engine, "ALTER TABLE attendance_history ADD COLUMN attendance_log_id INT NULL, ADD UNIQUE KEY uq_attendance_history_log_id (attendance_log_id)")
            if not _column_exists(engine, table="attendance_history", column="type", schema=schema):
                _exec(engine, "ALTER TABLE attendance_history ADD COLUMN type VARCHAR(16) NOT NULL DEFAULT 'checkin', ADD KEY ix_attendance_history_type (type)")
            if not _column_exists(engine, table="attendance_history", column="check_time", schema=schema):
                _exec(engine, "ALTER TABLE attendance_history ADD COLUMN check_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD KEY ix_attendance_history_check_time (check_time)")
            if not _column_exists(engine, table="attendance_history", column="confidence_score", schema=schema):
                _exec(engine, "ALTER TABLE attendance_history ADD COLUMN confidence_score DOUBLE NOT NULL DEFAULT 0.0")
            if not _column_exists(engine, table="attendance_history", column="image_url", schema=schema):
                _exec(engine, "ALTER TABLE attendance_history ADD COLUMN image_url VARCHAR(512) NULL")
            if not _column_exists(engine, table="attendance_history", column="image_size_kb", schema=schema):
                _exec(engine, "ALTER TABLE attendance_history ADD COLUMN image_size_kb INT NULL")
            if not _column_exists(engine, table="attendance_history", column="image_format", schema=schema):
                _exec(engine, "ALTER TABLE attendance_history ADD COLUMN image_format VARCHAR(16) NULL")
            if not _column_exists(engine, table="attendance_history", column="upload_status", schema=schema):
                _exec(engine, "ALTER TABLE attendance_history ADD COLUMN upload_status VARCHAR(16) NOT NULL DEFAULT 'pending', ADD KEY ix_attendance_history_upload_status (upload_status)")
            if not _column_exists(engine, table="attendance_history", column="created_at", schema=schema):
                _exec(engine, "ALTER TABLE attendance_history ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP")
            if not _column_exists(engine, table="attendance_history", column="updated_at", schema=schema):
                _exec(engine, "ALTER TABLE attendance_history ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP")

        if _table_exists(engine, table="attendance_evidence_settings", schema=schema):
            if not _column_exists(engine, table="attendance_evidence_settings", column="enable_evidence_image", schema=schema):
                _exec(engine, "ALTER TABLE attendance_evidence_settings ADD COLUMN enable_evidence_image TINYINT(1) NOT NULL DEFAULT 1")
            if not _column_exists(engine, table="attendance_evidence_settings", column="image_quality", schema=schema):
                _exec(engine, "ALTER TABLE attendance_evidence_settings ADD COLUMN image_quality INT NOT NULL DEFAULT 65")
            if not _column_exists(engine, table="attendance_evidence_settings", column="image_max_width", schema=schema):
                _exec(engine, "ALTER TABLE attendance_evidence_settings ADD COLUMN image_max_width INT NOT NULL DEFAULT 720")
            if not _column_exists(engine, table="attendance_evidence_settings", column="image_format", schema=schema):
                _exec(engine, "ALTER TABLE attendance_evidence_settings ADD COLUMN image_format VARCHAR(16) NOT NULL DEFAULT 'webp'")
            if not _column_exists(engine, table="attendance_evidence_settings", column="image_retention_days", schema=schema):
                _exec(engine, "ALTER TABLE attendance_evidence_settings ADD COLUMN image_retention_days INT NOT NULL DEFAULT 30")
            if not _column_exists(engine, table="attendance_evidence_settings", column="created_at", schema=schema):
                _exec(engine, "ALTER TABLE attendance_evidence_settings ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP")
            if not _column_exists(engine, table="attendance_evidence_settings", column="updated_at", schema=schema):
                _exec(engine, "ALTER TABLE attendance_evidence_settings ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP")

        if _table_exists(engine, table="attendance_evidence_tasks", schema=schema):
            if not _column_exists(engine, table="attendance_evidence_tasks", column="history_id", schema=schema):
                _exec(engine, "ALTER TABLE attendance_evidence_tasks ADD COLUMN history_id INT NOT NULL, ADD UNIQUE KEY uq_attendance_evidence_tasks_history_id (history_id)")
            if not _column_exists(engine, table="attendance_evidence_tasks", column="company_id", schema=schema):
                _exec(engine, "ALTER TABLE attendance_evidence_tasks ADD COLUMN company_id INT NULL, ADD KEY ix_attendance_evidence_tasks_company_id (company_id)")
            if not _column_exists(engine, table="attendance_evidence_tasks", column="employee_id", schema=schema):
                _exec(engine, "ALTER TABLE attendance_evidence_tasks ADD COLUMN employee_id INT NOT NULL, ADD KEY ix_attendance_evidence_tasks_employee_id (employee_id)")
            if not _column_exists(engine, table="attendance_evidence_tasks", column="spool_path", schema=schema):
                _exec(engine, "ALTER TABLE attendance_evidence_tasks ADD COLUMN spool_path VARCHAR(512) NOT NULL")
            if not _column_exists(engine, table="attendance_evidence_tasks", column="source_mime", schema=schema):
                _exec(engine, "ALTER TABLE attendance_evidence_tasks ADD COLUMN source_mime VARCHAR(64) NULL")
            if not _column_exists(engine, table="attendance_evidence_tasks", column="status", schema=schema):
                _exec(engine, "ALTER TABLE attendance_evidence_tasks ADD COLUMN status VARCHAR(16) NOT NULL DEFAULT 'pending', ADD KEY ix_attendance_evidence_tasks_status (status)")
            if not _column_exists(engine, table="attendance_evidence_tasks", column="attempts", schema=schema):
                _exec(engine, "ALTER TABLE attendance_evidence_tasks ADD COLUMN attempts INT NOT NULL DEFAULT 0")
            if not _column_exists(engine, table="attendance_evidence_tasks", column="max_attempts", schema=schema):
                _exec(engine, "ALTER TABLE attendance_evidence_tasks ADD COLUMN max_attempts INT NOT NULL DEFAULT 3")
            if not _column_exists(engine, table="attendance_evidence_tasks", column="next_attempt_at", schema=schema):
                _exec(engine, "ALTER TABLE attendance_evidence_tasks ADD COLUMN next_attempt_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD KEY ix_attendance_evidence_tasks_next_attempt_at (next_attempt_at)")
            if not _column_exists(engine, table="attendance_evidence_tasks", column="last_error", schema=schema):
                _exec(engine, "ALTER TABLE attendance_evidence_tasks ADD COLUMN last_error TEXT NULL")
            if not _column_exists(engine, table="attendance_evidence_tasks", column="created_at", schema=schema):
                _exec(engine, "ALTER TABLE attendance_evidence_tasks ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP")
            if not _column_exists(engine, table="attendance_evidence_tasks", column="updated_at", schema=schema):
                _exec(engine, "ALTER TABLE attendance_evidence_tasks ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP")
            if not _column_exists(engine, table="attendance_evidence_tasks", column="completed_at", schema=schema):
                _exec(engine, "ALTER TABLE attendance_evidence_tasks ADD COLUMN completed_at DATETIME NULL")
    except Exception:
        pass

    # leave_requests table (added later)
    # Keep migration best-effort: if table does not exist, skip.
    try:
        if not _column_exists(engine, table="leave_requests", column="status", schema=schema):
            # table exists but missing some column; do nothing special now
            pass
    except Exception:
        pass

    # work_schedule_registrations extensions (approval response note)
    try:
        if _table_exists(engine, table="work_schedule_registrations", schema=schema):
            if not _column_exists(engine, table="work_schedule_registrations", column="response_note", schema=schema):
                _exec(engine, "ALTER TABLE work_schedule_registrations ADD COLUMN response_note VARCHAR(255) NULL")
            if not _column_exists(engine, table="work_schedule_registrations", column="request_id", schema=schema):
                _exec(engine, "ALTER TABLE work_schedule_registrations ADD COLUMN request_id INT NULL, ADD KEY ix_work_schedule_registrations_request_id (request_id)")
    except Exception:
        pass

    # work_schedule_registration_requests table (batch approvals)
    try:
        if not _table_exists(engine, table="work_schedule_registration_requests", schema=schema):
            _exec(
                engine,
                """
                CREATE TABLE work_schedule_registration_requests (
                    id INT NOT NULL AUTO_INCREMENT,
                    company_id INT NOT NULL,
                    user_id INT NOT NULL,
                    schedule_id INT NOT NULL,
                    date_from DATE NOT NULL,
                    date_to DATE NOT NULL,
                    days_of_week_mask INT NOT NULL DEFAULT 127,
                    status VARCHAR(16) NOT NULL DEFAULT 'pending',
                    note VARCHAR(255) NULL,
                    response_note VARCHAR(255) NULL,
                    approved_by_user_id INT NULL,
                    approved_at DATETIME NULL,
                    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                    PRIMARY KEY (id),
                    KEY ix_wsrr_company_id (company_id),
                    KEY ix_wsrr_user_id (user_id),
                    KEY ix_wsrr_schedule_id (schedule_id),
                    KEY ix_wsrr_date_from (date_from),
                    KEY ix_wsrr_date_to (date_to),
                    KEY ix_wsrr_status (status),
                    KEY ix_wsrr_approved_by_user_id (approved_by_user_id)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
                """,
            )
    except Exception:
        pass

    # work_schedules extensions (index4: dept/max/days/range/note)
    try:
        if _table_exists(engine, table="work_schedules", schema=schema):
            if not _column_exists(engine, table="work_schedules", column="department_id", schema=schema):
                _exec(engine, "ALTER TABLE work_schedules ADD COLUMN department_id INT NULL, ADD KEY ix_work_schedules_department_id (department_id)")
            if not _column_exists(engine, table="work_schedules", column="max_registrations", schema=schema):
                _exec(engine, "ALTER TABLE work_schedules ADD COLUMN max_registrations INT NOT NULL DEFAULT 0")
            if not _column_exists(engine, table="work_schedules", column="days_of_week_mask", schema=schema):
                _exec(engine, "ALTER TABLE work_schedules ADD COLUMN days_of_week_mask INT NOT NULL DEFAULT 127")
            if not _column_exists(engine, table="work_schedules", column="date_start", schema=schema):
                _exec(engine, "ALTER TABLE work_schedules ADD COLUMN date_start DATE NULL")
            if not _column_exists(engine, table="work_schedules", column="date_end", schema=schema):
                _exec(engine, "ALTER TABLE work_schedules ADD COLUMN date_end DATE NULL")
            if not _column_exists(engine, table="work_schedules", column="note", schema=schema):
                _exec(engine, "ALTER TABLE work_schedules ADD COLUMN note VARCHAR(255) NULL")
    except Exception:
        pass

    # notifications tables
    try:
        if not _table_exists(engine, table="notifications", schema=schema):
            _exec(
                engine,
                """
                CREATE TABLE notifications (
                    id INT NOT NULL AUTO_INCREMENT,
                    company_id INT NULL,
                    type VARCHAR(64) NOT NULL,
                    category VARCHAR(32) NOT NULL,
                    severity VARCHAR(16) NOT NULL DEFAULT 'info',
                    title VARCHAR(255) NOT NULL,
                    body TEXT NULL,
                    entity_type VARCHAR(64) NULL,
                    entity_id INT NULL,
                    action_url VARCHAR(255) NULL,
                    created_by_user_id INT NULL,
                    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    PRIMARY KEY (id),
                    KEY ix_notifications_company_id (company_id),
                    KEY ix_notifications_type (type),
                    KEY ix_notifications_category (category),
                    KEY ix_notifications_severity (severity),
                    KEY ix_notifications_created_by_user_id (created_by_user_id),
                    KEY ix_notifications_created_at (created_at)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
                """,
            )
        if not _column_exists(engine, table="notifications", column="company_id", schema=schema):
            _exec(engine, "ALTER TABLE notifications ADD COLUMN company_id INT NULL, ADD KEY ix_notifications_company_id (company_id)")
        if not _column_exists(engine, table="notifications", column="type", schema=schema):
            _exec(engine, "ALTER TABLE notifications ADD COLUMN type VARCHAR(64) NOT NULL DEFAULT 'system.notice', ADD KEY ix_notifications_type (type)")
        else:
            type_meta = _get_column_meta(engine, table="notifications", column="type", schema=schema) or {}
            if "varchar" not in str(type_meta.get("COLUMN_TYPE", "")).lower():
                _exec(engine, "ALTER TABLE notifications MODIFY COLUMN type VARCHAR(64) NOT NULL")
            if not _index_exists(engine, table="notifications", index="ix_notifications_type", schema=schema):
                _exec(engine, "ALTER TABLE notifications ADD KEY ix_notifications_type (type)")
        if not _column_exists(engine, table="notifications", column="category", schema=schema):
            _exec(engine, "ALTER TABLE notifications ADD COLUMN category VARCHAR(32) NOT NULL DEFAULT 'system', ADD KEY ix_notifications_category (category)")
        if not _column_exists(engine, table="notifications", column="severity", schema=schema):
            _exec(engine, "ALTER TABLE notifications ADD COLUMN severity VARCHAR(16) NOT NULL DEFAULT 'info', ADD KEY ix_notifications_severity (severity)")
        else:
            severity_meta = _get_column_meta(engine, table="notifications", column="severity", schema=schema) or {}
            if "varchar" not in str(severity_meta.get("COLUMN_TYPE", "")).lower():
                _exec(engine, "ALTER TABLE notifications MODIFY COLUMN severity VARCHAR(16) NOT NULL DEFAULT 'info'")
            if not _index_exists(engine, table="notifications", index="ix_notifications_severity", schema=schema):
                _exec(engine, "ALTER TABLE notifications ADD KEY ix_notifications_severity (severity)")
        if not _column_exists(engine, table="notifications", column="title", schema=schema):
            _exec(engine, "ALTER TABLE notifications ADD COLUMN title VARCHAR(255) NOT NULL DEFAULT 'Thông báo'")
        if not _column_exists(engine, table="notifications", column="body", schema=schema):
            _exec(engine, "ALTER TABLE notifications ADD COLUMN body TEXT NULL")
        else:
            body_meta = _get_column_meta(engine, table="notifications", column="body", schema=schema) or {}
            if "text" not in str(body_meta.get("COLUMN_TYPE", "")).lower():
                _exec(engine, "ALTER TABLE notifications MODIFY COLUMN body TEXT NULL")
        if not _column_exists(engine, table="notifications", column="entity_type", schema=schema):
            _exec(engine, "ALTER TABLE notifications ADD COLUMN entity_type VARCHAR(64) NULL")
        if not _column_exists(engine, table="notifications", column="entity_id", schema=schema):
            _exec(engine, "ALTER TABLE notifications ADD COLUMN entity_id INT NULL")
        if not _column_exists(engine, table="notifications", column="action_url", schema=schema):
            _exec(engine, "ALTER TABLE notifications ADD COLUMN action_url VARCHAR(255) NULL")
        if not _column_exists(engine, table="notifications", column="created_by_user_id", schema=schema):
            _exec(engine, "ALTER TABLE notifications ADD COLUMN created_by_user_id INT NULL, ADD KEY ix_notifications_created_by_user_id (created_by_user_id)")
        if not _column_exists(engine, table="notifications", column="created_at", schema=schema):
            _exec(engine, "ALTER TABLE notifications ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD KEY ix_notifications_created_at (created_at)")
        else:
            created_at_meta = _get_column_meta(engine, table="notifications", column="created_at", schema=schema) or {}
            if str(created_at_meta.get("IS_NULLABLE", "")).upper() != "NO" or created_at_meta.get("COLUMN_DEFAULT") != "CURRENT_TIMESTAMP":
                _exec(engine, "ALTER TABLE notifications MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP")
            if not _index_exists(engine, table="notifications", index="ix_notifications_created_at", schema=schema):
                _exec(engine, "ALTER TABLE notifications ADD KEY ix_notifications_created_at (created_at)")
        if _column_exists(engine, table="notifications", column="user_id", schema=schema):
            user_id_meta = _get_column_meta(engine, table="notifications", column="user_id", schema=schema) or {}
            if str(user_id_meta.get("IS_NULLABLE", "")).upper() != "YES":
                _exec(engine, "ALTER TABLE notifications MODIFY COLUMN user_id INT NULL")
        if not _table_exists(engine, table="notification_recipients", schema=schema):
            _exec(
                engine,
                """
                CREATE TABLE notification_recipients (
                    id INT NOT NULL AUTO_INCREMENT,
                    notification_id INT NOT NULL,
                    user_id INT NOT NULL,
                    is_read TINYINT(1) NOT NULL DEFAULT 0,
                    read_at DATETIME NULL,
                    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    PRIMARY KEY (id),
                    UNIQUE KEY uq_notification_recipient_user (notification_id, user_id),
                    KEY ix_notification_recipients_notification_id (notification_id),
                    KEY ix_notification_recipients_user_id (user_id),
                    KEY ix_notification_recipients_is_read (is_read)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
                """,
            )
        if not _column_exists(engine, table="notification_recipients", column="notification_id", schema=schema):
            _exec(engine, "ALTER TABLE notification_recipients ADD COLUMN notification_id INT NOT NULL, ADD KEY ix_notification_recipients_notification_id (notification_id)")
        if not _column_exists(engine, table="notification_recipients", column="user_id", schema=schema):
            _exec(engine, "ALTER TABLE notification_recipients ADD COLUMN user_id INT NOT NULL, ADD KEY ix_notification_recipients_user_id (user_id)")
        if not _column_exists(engine, table="notification_recipients", column="is_read", schema=schema):
            _exec(engine, "ALTER TABLE notification_recipients ADD COLUMN is_read TINYINT(1) NOT NULL DEFAULT 0, ADD KEY ix_notification_recipients_is_read (is_read)")
        if not _column_exists(engine, table="notification_recipients", column="read_at", schema=schema):
            _exec(engine, "ALTER TABLE notification_recipients ADD COLUMN read_at DATETIME NULL")
        if not _column_exists(engine, table="notification_recipients", column="created_at", schema=schema):
            _exec(engine, "ALTER TABLE notification_recipients ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP")
        if not _column_exists(engine, table="notification_recipients", column="archived_at", schema=schema):
            _exec(engine, "ALTER TABLE notification_recipients ADD COLUMN archived_at DATETIME NULL, ADD KEY ix_notification_recipients_archived_at (archived_at)")
        if _column_exists(engine, table="notifications", column="user_id", schema=schema):
            _exec(
                engine,
                """
                INSERT IGNORE INTO notification_recipients (notification_id, user_id, is_read, read_at, created_at)
                SELECT
                    n.id,
                    n.user_id,
                    COALESCE(n.read, 0),
                    CASE WHEN COALESCE(n.read, 0) = 1 THEN COALESCE(n.created_at, CURRENT_TIMESTAMP) ELSE NULL END,
                    COALESCE(n.created_at, CURRENT_TIMESTAMP)
                FROM notifications n
                WHERE n.user_id IS NOT NULL
                """,
            )
        if not _table_exists(engine, table="notification_preferences", schema=schema):
            _exec(
                engine,
                """
                CREATE TABLE notification_preferences (
                    id INT NOT NULL AUTO_INCREMENT,
                    user_id INT NOT NULL,
                    realtime_toast_enabled TINYINT(1) NOT NULL DEFAULT 1,
                    attendance_enabled TINYINT(1) NOT NULL DEFAULT 1,
                    leave_enabled TINYINT(1) NOT NULL DEFAULT 1,
                    schedule_enabled TINYINT(1) NOT NULL DEFAULT 1,
                    settings_enabled TINYINT(1) NOT NULL DEFAULT 1,
                    iam_enabled TINYINT(1) NOT NULL DEFAULT 1,
                    system_enabled TINYINT(1) NOT NULL DEFAULT 1,
                    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                    PRIMARY KEY (id),
                    UNIQUE KEY uq_notification_preferences_user (user_id),
                    KEY ix_notification_preferences_user_id (user_id)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
                """,
            )
        if not _column_exists(engine, table="notification_preferences", column="user_id", schema=schema):
            _exec(engine, "ALTER TABLE notification_preferences ADD COLUMN user_id INT NOT NULL, ADD KEY ix_notification_preferences_user_id (user_id)")
        if not _column_exists(engine, table="notification_preferences", column="realtime_toast_enabled", schema=schema):
            _exec(engine, "ALTER TABLE notification_preferences ADD COLUMN realtime_toast_enabled TINYINT(1) NOT NULL DEFAULT 1")
        if not _column_exists(engine, table="notification_preferences", column="attendance_enabled", schema=schema):
            _exec(engine, "ALTER TABLE notification_preferences ADD COLUMN attendance_enabled TINYINT(1) NOT NULL DEFAULT 1")
        if not _column_exists(engine, table="notification_preferences", column="leave_enabled", schema=schema):
            _exec(engine, "ALTER TABLE notification_preferences ADD COLUMN leave_enabled TINYINT(1) NOT NULL DEFAULT 1")
        if not _column_exists(engine, table="notification_preferences", column="schedule_enabled", schema=schema):
            _exec(engine, "ALTER TABLE notification_preferences ADD COLUMN schedule_enabled TINYINT(1) NOT NULL DEFAULT 1")
        if not _column_exists(engine, table="notification_preferences", column="settings_enabled", schema=schema):
            _exec(engine, "ALTER TABLE notification_preferences ADD COLUMN settings_enabled TINYINT(1) NOT NULL DEFAULT 1")
        if not _column_exists(engine, table="notification_preferences", column="iam_enabled", schema=schema):
            _exec(engine, "ALTER TABLE notification_preferences ADD COLUMN iam_enabled TINYINT(1) NOT NULL DEFAULT 1")
        if not _column_exists(engine, table="notification_preferences", column="system_enabled", schema=schema):
            _exec(engine, "ALTER TABLE notification_preferences ADD COLUMN system_enabled TINYINT(1) NOT NULL DEFAULT 1")
        if not _column_exists(engine, table="notification_preferences", column="created_at", schema=schema):
            _exec(engine, "ALTER TABLE notification_preferences ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP")
        if not _column_exists(engine, table="notification_preferences", column="updated_at", schema=schema):
            _exec(engine, "ALTER TABLE notification_preferences ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP")
        if not _table_exists(engine, table="company_notification_policies", schema=schema):
            _exec(
                engine,
                """
                CREATE TABLE company_notification_policies (
                    id INT NOT NULL AUTO_INCREMENT,
                    company_id INT NOT NULL,
                    late_attendance_enabled TINYINT(1) NOT NULL DEFAULT 1,
                    absent_attendance_enabled TINYINT(1) NOT NULL DEFAULT 1,
                    new_leave_request_enabled TINYINT(1) NOT NULL DEFAULT 1,
                    daily_report_enabled TINYINT(1) NOT NULL DEFAULT 0,
                    overtime_request_enabled TINYINT(1) NOT NULL DEFAULT 1,
                    attendance_policy_change_enabled TINYINT(1) NOT NULL DEFAULT 1,
                    gps_policy_change_enabled TINYINT(1) NOT NULL DEFAULT 1,
                    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                    PRIMARY KEY (id),
                    UNIQUE KEY uq_company_notification_policies_company (company_id),
                    KEY ix_company_notification_policies_company_id (company_id)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
                """,
            )
        if not _column_exists(engine, table="company_notification_policies", column="company_id", schema=schema):
            _exec(engine, "ALTER TABLE company_notification_policies ADD COLUMN company_id INT NOT NULL, ADD KEY ix_company_notification_policies_company_id (company_id)")
        if not _column_exists(engine, table="company_notification_policies", column="late_attendance_enabled", schema=schema):
            _exec(engine, "ALTER TABLE company_notification_policies ADD COLUMN late_attendance_enabled TINYINT(1) NOT NULL DEFAULT 1")
        if not _column_exists(engine, table="company_notification_policies", column="absent_attendance_enabled", schema=schema):
            _exec(engine, "ALTER TABLE company_notification_policies ADD COLUMN absent_attendance_enabled TINYINT(1) NOT NULL DEFAULT 1")
        if not _column_exists(engine, table="company_notification_policies", column="new_leave_request_enabled", schema=schema):
            _exec(engine, "ALTER TABLE company_notification_policies ADD COLUMN new_leave_request_enabled TINYINT(1) NOT NULL DEFAULT 1")
        if not _column_exists(engine, table="company_notification_policies", column="daily_report_enabled", schema=schema):
            _exec(engine, "ALTER TABLE company_notification_policies ADD COLUMN daily_report_enabled TINYINT(1) NOT NULL DEFAULT 0")
        if not _column_exists(engine, table="company_notification_policies", column="overtime_request_enabled", schema=schema):
            _exec(engine, "ALTER TABLE company_notification_policies ADD COLUMN overtime_request_enabled TINYINT(1) NOT NULL DEFAULT 1")
        if not _column_exists(engine, table="company_notification_policies", column="attendance_policy_change_enabled", schema=schema):
            _exec(engine, "ALTER TABLE company_notification_policies ADD COLUMN attendance_policy_change_enabled TINYINT(1) NOT NULL DEFAULT 1")
        if not _column_exists(engine, table="company_notification_policies", column="gps_policy_change_enabled", schema=schema):
            _exec(engine, "ALTER TABLE company_notification_policies ADD COLUMN gps_policy_change_enabled TINYINT(1) NOT NULL DEFAULT 1")
        if not _column_exists(engine, table="company_notification_policies", column="created_at", schema=schema):
            _exec(engine, "ALTER TABLE company_notification_policies ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP")
        if not _column_exists(engine, table="company_notification_policies", column="updated_at", schema=schema):
            _exec(engine, "ALTER TABLE company_notification_policies ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP")
    except Exception:
        pass
