from __future__ import annotations

from sqlalchemy import Engine, text


def _column_exists(engine: Engine, *, table: str, column: str, schema: str) -> bool:
    q = text(
        """
        SELECT COUNT(*) AS c
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = :schema AND TABLE_NAME = :table AND COLUMN_NAME = :column
        """
    )
    with engine.connect() as conn:
        c = conn.execute(q, {"schema": schema, "table": table, "column": column}).scalar_one()
        return int(c or 0) > 0


def _table_exists(engine: Engine, *, table: str, schema: str) -> bool:
    q = text(
        """
        SELECT COUNT(*) AS c
        FROM INFORMATION_SCHEMA.TABLES
        WHERE TABLE_SCHEMA = :schema AND TABLE_NAME = :table
        """
    )
    with engine.connect() as conn:
        c = conn.execute(q, {"schema": schema, "table": table}).scalar_one()
        return int(c or 0) > 0


def _exec(engine: Engine, sql: str) -> None:
    with engine.begin() as conn:
        conn.execute(text(sql))

def _index_exists(engine: Engine, *, table: str, index: str, schema: str) -> bool:
    q = text(
        """
        SELECT COUNT(*) AS c
        FROM INFORMATION_SCHEMA.STATISTICS
        WHERE TABLE_SCHEMA = :schema AND TABLE_NAME = :table AND INDEX_NAME = :index
        """
    )
    with engine.connect() as conn:
        c = conn.execute(q, {"schema": schema, "table": table, "index": index}).scalar_one()
        return int(c or 0) > 0


def _list_unique_single_column_indexes(
    engine: Engine, *, table: str, column: str, schema: str
) -> list[str]:
    """
    Return names of UNIQUE indexes that cover exactly one column and that column matches `column`.

    This is used to clean up older schemas where `email` might have had a global UNIQUE constraint
    with a different index name (e.g. auto-generated by a previous ORM/migration).
    """
    q = text(
        """
        SELECT INDEX_NAME
        FROM INFORMATION_SCHEMA.STATISTICS
        WHERE TABLE_SCHEMA = :schema
          AND TABLE_NAME = :table
          AND NON_UNIQUE = 0
        GROUP BY INDEX_NAME
        HAVING COUNT(*) = 1
           AND SUM(CASE WHEN COLUMN_NAME = :column THEN 1 ELSE 0 END) = 1
        """
    )
    with engine.connect() as conn:
        rows = conn.execute(q, {"schema": schema, "table": table, "column": column}).all()
        return [r[0] for r in rows if r and r[0] and str(r[0]).upper() != "PRIMARY"]


def run_lightweight_migrations(engine: Engine, *, schema: str) -> None:
    """
    Minimal, non-Alembic migrations for local/dev:
    - Add missing columns for business fields (users, departments)
    This is best-effort: safe to run multiple times.
    """

    # users table extensions (if project was created before these fields existed)
    if not _column_exists(engine, table="users", column="company_id", schema=schema):
        _exec(engine, "ALTER TABLE users ADD COLUMN company_id INT NULL, ADD KEY ix_users_company_id (company_id)")
    if not _column_exists(engine, table="users", column="username", schema=schema):
        _exec(engine, "ALTER TABLE users ADD COLUMN username VARCHAR(64) NULL, ADD UNIQUE KEY uq_users_username (username), ADD KEY ix_users_username (username)")
    if not _column_exists(engine, table="users", column="password_hash", schema=schema):
        _exec(engine, "ALTER TABLE users ADD COLUMN password_hash VARCHAR(255) NULL")
    if not _column_exists(engine, table="users", column="auth_status", schema=schema):
        _exec(engine, "ALTER TABLE users ADD COLUMN auth_status VARCHAR(16) NOT NULL DEFAULT 'active'")
    if not _column_exists(engine, table="users", column="invite_token_hash", schema=schema):
        _exec(engine, "ALTER TABLE users ADD COLUMN invite_token_hash VARCHAR(255) NULL")
    if not _column_exists(engine, table="users", column="invite_token_expires_at", schema=schema):
        _exec(engine, "ALTER TABLE users ADD COLUMN invite_token_expires_at DATETIME NULL")
    if not _column_exists(engine, table="users", column="invite_sent_at", schema=schema):
        _exec(engine, "ALTER TABLE users ADD COLUMN invite_sent_at DATETIME NULL")
    if not _column_exists(engine, table="users", column="invite_accepted_at", schema=schema):
        _exec(engine, "ALTER TABLE users ADD COLUMN invite_accepted_at DATETIME NULL")
    if not _column_exists(engine, table="users", column="code", schema=schema):
        _exec(engine, "ALTER TABLE users ADD COLUMN code VARCHAR(32) NULL")
    # Employee code uniqueness is scoped to company: allow same code across different companies.
    if _index_exists(engine, table="users", index="uq_users_code", schema=schema):
        _exec(engine, "ALTER TABLE users DROP INDEX uq_users_code")
    for idx in _list_unique_single_column_indexes(engine, table="users", column="code", schema=schema):
        _exec(engine, f"ALTER TABLE users DROP INDEX {idx}")
    if not _index_exists(engine, table="users", index="uq_users_company_code", schema=schema):
        _exec(engine, "ALTER TABLE users ADD UNIQUE KEY uq_users_company_code (company_id, code)")
    if not _column_exists(engine, table="users", column="email", schema=schema):
        _exec(engine, "ALTER TABLE users ADD COLUMN email VARCHAR(255) NULL")
    # Email uniqueness is scoped to company: allow same email across different companies.
    if _index_exists(engine, table="users", index="uq_users_email", schema=schema):
        _exec(engine, "ALTER TABLE users DROP INDEX uq_users_email")
    # Drop any legacy global UNIQUE(email) index regardless of its name.
    for idx in _list_unique_single_column_indexes(engine, table="users", column="email", schema=schema):
        _exec(engine, f"ALTER TABLE users DROP INDEX {idx}")
    if not _index_exists(engine, table="users", index="uq_users_company_email", schema=schema):
        _exec(engine, "ALTER TABLE users ADD UNIQUE KEY uq_users_company_email (company_id, email)")
    if not _index_exists(engine, table="users", index="ix_users_email", schema=schema):
        _exec(engine, "ALTER TABLE users ADD KEY ix_users_email (email)")
    if not _column_exists(engine, table="users", column="role", schema=schema):
        _exec(engine, "ALTER TABLE users ADD COLUMN role VARCHAR(64) NULL")
    if not _column_exists(engine, table="users", column="status", schema=schema):
        _exec(engine, "ALTER TABLE users ADD COLUMN status VARCHAR(16) NOT NULL DEFAULT 'active'")
    if not _column_exists(engine, table="users", column="department_id", schema=schema):
        _exec(engine, "ALTER TABLE users ADD COLUMN department_id INT NULL, ADD KEY ix_users_department_id (department_id)")

    # departments table extensions
    if not _column_exists(engine, table="departments", column="company_id", schema=schema):
        _exec(engine, "ALTER TABLE departments ADD COLUMN company_id INT NULL, ADD KEY ix_departments_company_id (company_id)")

    # companies table extensions (geo-fence settings)
    if _table_exists(engine, table="companies", schema=schema):
        if not _column_exists(engine, table="companies", column="address", schema=schema):
            _exec(engine, "ALTER TABLE companies ADD COLUMN address VARCHAR(255) NULL")
        if not _column_exists(engine, table="companies", column="latitude", schema=schema):
            _exec(engine, "ALTER TABLE companies ADD COLUMN latitude DOUBLE NULL")
        if not _column_exists(engine, table="companies", column="longitude", schema=schema):
            _exec(engine, "ALTER TABLE companies ADD COLUMN longitude DOUBLE NULL")
    if not _column_exists(engine, table="companies", column="geo_radius_meters", schema=schema):
        _exec(engine, "ALTER TABLE companies ADD COLUMN geo_radius_meters DOUBLE NULL")
    if not _column_exists(engine, table="companies", column="require_gps_on_attendance", schema=schema):
        _exec(engine, "ALTER TABLE companies ADD COLUMN require_gps_on_attendance TINYINT(1) NOT NULL DEFAULT 0")

    # IAM join tables (new): user_roles, user_permissions
    if not _table_exists(engine, table="user_roles", schema=schema):
        _exec(
            engine,
            """
            CREATE TABLE user_roles (
              id INT AUTO_INCREMENT PRIMARY KEY,
              user_id INT NOT NULL,
              role_id INT NOT NULL,
              created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
              UNIQUE KEY uq_user_roles (user_id, role_id),
              KEY ix_user_roles_user_id (user_id),
              KEY ix_user_roles_role_id (role_id),
              CONSTRAINT fk_user_roles_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
              CONSTRAINT fk_user_roles_role_id FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
            )
            """,
        )
    if not _table_exists(engine, table="user_permissions", schema=schema):
        _exec(
            engine,
            """
            CREATE TABLE user_permissions (
              id INT AUTO_INCREMENT PRIMARY KEY,
              user_id INT NOT NULL,
              permission_id INT NOT NULL,
              created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
              UNIQUE KEY uq_user_permissions (user_id, permission_id),
              KEY ix_user_permissions_user_id (user_id),
              KEY ix_user_permissions_permission_id (permission_id),
              CONSTRAINT fk_user_permissions_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
              CONSTRAINT fk_user_permissions_permission_id FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
            )
            """,
        )

    # Best-effort data migration from legacy IAM tables (accounts/account_roles/account_permissions).
    if _table_exists(engine, table="accounts", schema=schema):
        try:
            # 1) Move account rows into users (by username).
            _exec(
                engine,
                """
                INSERT IGNORE INTO users (username, password_hash, name)
                SELECT a.username, a.password_hash, a.username
                FROM accounts a
                """,
            )
            # 2) Move role assignments by username mapping.
            if _table_exists(engine, table="account_roles", schema=schema):
                _exec(
                    engine,
                    """
                    INSERT IGNORE INTO user_roles (user_id, role_id)
                    SELECT u.id, ar.role_id
                    FROM account_roles ar
                    JOIN accounts a ON a.id = ar.account_id
                    JOIN users u ON u.username = a.username
                    """,
                )
            # 3) Move direct permission assignments by username mapping.
            if _table_exists(engine, table="account_permissions", schema=schema):
                _exec(
                    engine,
                    """
                    INSERT IGNORE INTO user_permissions (user_id, permission_id)
                    SELECT u.id, ap.permission_id
                    FROM account_permissions ap
                    JOIN accounts a ON a.id = ap.account_id
                    JOIN users u ON u.username = a.username
                    """,
                )
        except Exception:
            # Migration is best-effort; ignore any failures due to partial schema differences.
            pass

    # attendance_policies table extensions
    if not _column_exists(engine, table="attendance_policies", column="timezone", schema=schema):
        _exec(engine, "ALTER TABLE attendance_policies ADD COLUMN timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Ho_Chi_Minh'")
    if not _column_exists(engine, table="attendance_policies", column="face_match_threshold", schema=schema):
        _exec(engine, "ALTER TABLE attendance_policies ADD COLUMN face_match_threshold DOUBLE NOT NULL DEFAULT 0.5")
    if not _column_exists(engine, table="attendance_policies", column="shift_end", schema=schema):
        _exec(engine, "ALTER TABLE attendance_policies ADD COLUMN shift_end VARCHAR(5) NOT NULL DEFAULT '18:00'")
    if not _column_exists(engine, table="attendance_policies", column="early_leave_grace_minutes", schema=schema):
        _exec(engine, "ALTER TABLE attendance_policies ADD COLUMN early_leave_grace_minutes INT NOT NULL DEFAULT 0")
    if not _column_exists(engine, table="attendance_policies", column="break_start", schema=schema):
        _exec(engine, "ALTER TABLE attendance_policies ADD COLUMN break_start VARCHAR(5) NOT NULL DEFAULT '12:00'")
    if not _column_exists(engine, table="attendance_policies", column="break_end", schema=schema):
        _exec(engine, "ALTER TABLE attendance_policies ADD COLUMN break_end VARCHAR(5) NOT NULL DEFAULT '13:00'")
    if not _column_exists(engine, table="attendance_policies", column="break_duration_minutes", schema=schema):
        _exec(engine, "ALTER TABLE attendance_policies ADD COLUMN break_duration_minutes INT NOT NULL DEFAULT 60")
    if not _column_exists(engine, table="attendance_policies", column="break_threshold_hours", schema=schema):
        _exec(engine, "ALTER TABLE attendance_policies ADD COLUMN break_threshold_hours DOUBLE NOT NULL DEFAULT 6.0")
    if not _column_exists(engine, table="attendance_policies", column="auto_checkout_time", schema=schema):
        _exec(engine, "ALTER TABLE attendance_policies ADD COLUMN auto_checkout_time VARCHAR(5) NOT NULL DEFAULT '23:59'")

    # users table extensions
    if not _column_exists(engine, table="users", column="face_enrolled_at", schema=schema):
        _exec(engine, "ALTER TABLE users ADD COLUMN face_enrolled_at DATETIME NULL")

    # attendance_logs geo fields
    if not _column_exists(engine, table="attendance_logs", column="latitude", schema=schema):
        _exec(engine, "ALTER TABLE attendance_logs ADD COLUMN latitude DOUBLE NULL")
    if not _column_exists(engine, table="attendance_logs", column="longitude", schema=schema):
        _exec(engine, "ALTER TABLE attendance_logs ADD COLUMN longitude DOUBLE NULL")
    if not _column_exists(engine, table="attendance_logs", column="distance_meters", schema=schema):
        _exec(engine, "ALTER TABLE attendance_logs ADD COLUMN distance_meters DOUBLE NULL")
    if not _column_exists(engine, table="attendance_logs", column="geo_ok", schema=schema):
        _exec(engine, "ALTER TABLE attendance_logs ADD COLUMN geo_ok TINYINT(1) NOT NULL DEFAULT 1")

    # leave_requests table (added later)
    # Keep migration best-effort: if table does not exist, skip.
    try:
        if not _column_exists(engine, table="leave_requests", column="status", schema=schema):
            # table exists but missing some column; do nothing special now
            pass
    except Exception:
        pass

    # work_schedule_registrations extensions (approval response note)
    try:
        if _table_exists(engine, table="work_schedule_registrations", schema=schema):
            if not _column_exists(engine, table="work_schedule_registrations", column="response_note", schema=schema):
                _exec(engine, "ALTER TABLE work_schedule_registrations ADD COLUMN response_note VARCHAR(255) NULL")
            if not _column_exists(engine, table="work_schedule_registrations", column="request_id", schema=schema):
                _exec(engine, "ALTER TABLE work_schedule_registrations ADD COLUMN request_id INT NULL, ADD KEY ix_work_schedule_registrations_request_id (request_id)")
    except Exception:
        pass

    # work_schedule_registration_requests table (batch approvals)
    try:
        if not _table_exists(engine, table="work_schedule_registration_requests", schema=schema):
            _exec(
                engine,
                """
                CREATE TABLE work_schedule_registration_requests (
                    id INT NOT NULL AUTO_INCREMENT,
                    company_id INT NOT NULL,
                    user_id INT NOT NULL,
                    schedule_id INT NOT NULL,
                    date_from DATE NOT NULL,
                    date_to DATE NOT NULL,
                    days_of_week_mask INT NOT NULL DEFAULT 127,
                    status VARCHAR(16) NOT NULL DEFAULT 'pending',
                    note VARCHAR(255) NULL,
                    response_note VARCHAR(255) NULL,
                    approved_by_user_id INT NULL,
                    approved_at DATETIME NULL,
                    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                    PRIMARY KEY (id),
                    KEY ix_wsrr_company_id (company_id),
                    KEY ix_wsrr_user_id (user_id),
                    KEY ix_wsrr_schedule_id (schedule_id),
                    KEY ix_wsrr_date_from (date_from),
                    KEY ix_wsrr_date_to (date_to),
                    KEY ix_wsrr_status (status),
                    KEY ix_wsrr_approved_by_user_id (approved_by_user_id)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
                """,
            )
    except Exception:
        pass

    # work_schedules extensions (index4: dept/max/days/range/note)
    try:
        if _table_exists(engine, table="work_schedules", schema=schema):
            if not _column_exists(engine, table="work_schedules", column="department_id", schema=schema):
                _exec(engine, "ALTER TABLE work_schedules ADD COLUMN department_id INT NULL, ADD KEY ix_work_schedules_department_id (department_id)")
            if not _column_exists(engine, table="work_schedules", column="max_registrations", schema=schema):
                _exec(engine, "ALTER TABLE work_schedules ADD COLUMN max_registrations INT NOT NULL DEFAULT 0")
            if not _column_exists(engine, table="work_schedules", column="days_of_week_mask", schema=schema):
                _exec(engine, "ALTER TABLE work_schedules ADD COLUMN days_of_week_mask INT NOT NULL DEFAULT 127")
            if not _column_exists(engine, table="work_schedules", column="date_start", schema=schema):
                _exec(engine, "ALTER TABLE work_schedules ADD COLUMN date_start DATE NULL")
            if not _column_exists(engine, table="work_schedules", column="date_end", schema=schema):
                _exec(engine, "ALTER TABLE work_schedules ADD COLUMN date_end DATE NULL")
            if not _column_exists(engine, table="work_schedules", column="note", schema=schema):
                _exec(engine, "ALTER TABLE work_schedules ADD COLUMN note VARCHAR(255) NULL")
    except Exception:
        pass
